kind: pipeline
name: redwood

# Limits Drone to running one pipeline at a time. This will prevent
# pipelines from being run concurrently. This is useful if you want to
# prevent two or more deployments to be run in parallel.
concurrency:
  limit: 1

steps:
  - name: backend
    image: python:3.6.8
    environment:
      HEROKU_API_KEY:
        from_secret: HEROKU_API_KEY
    commands:
      - pip3 install -r requirements.txt
      - python3 test_redwood.py
      - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/redwood-prod.git master
