version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Python dependencies in a virtual environment
          command: |
            python3 -m venv venv
            venv/bin/pip3 install -r requirements.txt
      - run:
          name: Run tests
          command: |
            venv/bin/python3 test_redwood.py
      - store_artifacts:
          path: test-reports
          destination: reports
      - store_test_results:
          path: test-reports/
