version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.5-stretch
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Python deps in a venv
          command: |
            pip3 install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python3 test_redwood.py
      - store_artifacts:
          path: test-reports
          destination: reports
      - store_test_results:
          path: test-reports/
